# Generated by Django 5.2 on 2025-07-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geocoder_cache", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocodercache",
            name="address",
            field=models.CharField(max_length=200, unique=True, verbose_name="адрес"),
        ),
        migrations.AddIndex(
            model_name="geocodercache",
            index=models.Index(
                fields=["requested_at"], name="geocoder_ca_request_99be38_idx"
            ),
        ),
    ]
