# Generated by Django 5.2 on 2025-07-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeocoderCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_index=True, max_length=200, unique=True, verbose_name="адрес"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="широта"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="долгота"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата запроса"
                    ),
                ),
            ],
            options={
                "verbose_name": "кэш геокодера",
                "verbose_name_plural": "кэш геокодера",
                "indexes": [
                    models.Index(
                        fields=["address"], name="geocoder_ca_address_90dc58_idx"
                    )
                ],
            },
        ),
    ]
