# Generated by Django 5.2.4 on 2025-07-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0052_restaurant_location"),
        ("geocoder_cache", "0002_alter_geocodercache_address_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GeocoderCache",
            new_name="GeoPlace",
        ),
        migrations.AlterModelOptions(
            name="geoplace",
            options={
                "verbose_name": "географическое место",
                "verbose_name_plural": "географические места",
            },
        ),
        migrations.RenameIndex(
            model_name="geoplace",
            new_name="geocoder_ca_address_dcb90d_idx",
            old_name="geocoder_ca_address_90dc58_idx",
        ),
        migrations.RenameIndex(
            model_name="geoplace",
            new_name="geocoder_ca_request_a6b7e5_idx",
            old_name="geocoder_ca_request_99be38_idx",
        ),
    ]
