# Generated by Django 5.2.4 on 2025-07-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0038_order_orderitem"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="foodcartapp_created_cd8d79_idx",
        ),
    ]
