# Generated by Django 5.2 on 2025-07-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0042_make_orderitem_price_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("confirmed", "Подтверждён"),
                    ("preparing", "Готовится"),
                    ("delivering", "В пути"),
                    ("completed", "Выполнен"),
                ],
                db_index=True,
                default="new",
                max_length=20,
                verbose_name="статус",
            ),
        ),
    ]
