# Generated by Django 5.2 on 2025-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0043_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("confirmed", "Подтверждён"),
                    ("preparing", "Готовится"),
                    ("delivering", "В пути"),
                    ("completed", "Выполнен"),
                ],
                default="new",
                max_length=20,
                verbose_name="статус",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="foodcartapp_status_99d57e_idx"),
        ),
    ]
