# Generated by Django 5.2 on 2025-07-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0045_order_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время звонка клиенту",
                null=True,
                verbose_name="дата звонка",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время доставки заказа",
                null=True,
                verbose_name="дата доставки",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["called_at"], name="foodcartapp_called__a766dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["delivered_at"], name="foodcartapp_deliver_0afa88_idx"
            ),
        ),
    ]
