# Generated by Django 5.2 on 2025-07-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0047_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("online", "Онлайн"), ("cash", "Наличными")],
                default="online",
                max_length=20,
                verbose_name="способ оплаты",
            ),
        ),
    ]
