# Generated by Django 5.2.4 on 2025-07-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0052_restaurant_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="location",
        ),
    ]
