# Generated by Django 5.2.4 on 2025-07-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0053_remove_restaurant_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=200, verbose_name="адрес доставки"),
        ),
    ]
