# Generated by Django 5.2 on 2025-07-19 13:46

from django.db import migrations


def fill_orderitem_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for order_item in OrderItem.objects.select_related('product').iterator():
        order_item.price = order_item.product.price
        order_item.save(update_fields=['price'])


def reverse_fill_orderitem_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    OrderItem.objects.update(price=None)


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0040_add_price_field_to_orderitem"),
    ]

    operations = [
        migrations.RunPython(
            fill_orderitem_price,
            reverse_fill_orderitem_price,
        ),
    ]
