# Generated by Django 5.2 on 2025-07-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0046_order_called_at_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("electronic", "Электронно"),
                    ("cash", "Наличностью при доставке"),
                ],
                default="cash",
                max_length=20,
                verbose_name="способ оплаты",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_method"], name="foodcartapp_payment_2918c1_idx"
            ),
        ),
    ]
